Repository smRt-Egg/BE-05-smRt-store, pull requests merged in 2023-12, with the labels that each got.

#14 [CHORE] ci 부분에 대한 파일 작성
  .github/workflows/ci_gradle.yml
Labels: 🧹 Chore, 🚀 Infra

#16 Chore/#13 cicd
  .github/workflows/cd_gradle.yml
  .github/workflows/ci_gradle.yml
  .gitignore
  Dockerfile
  src/main/resources/application.properties
Labels: 🧹 Chore, 🚀 Infra

#17 [CHORE] cd 스크립트 application 파일 로직 변경
  .github/workflows/cd_gradle.yml
Labels: 🧹 Chore, 🚀 Infra

#24 [FEAT] data jpa 의존성 추가
  build.gradle
Labels: 🧹 Chore

#21 Feat/#2 order interface
  src/main/java/com/programmers/smrtstore/domain/order/application/OrderService.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/Order.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/OrderedProduct.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/ShippingInfo.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/enums/OrderStatus.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/enums/PaymentMethod.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/req/CreateOrderRequest.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/req/CreateOrderSheetRequest.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/req/UpdateOrderRequest.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/res/CreateOrderResponse.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/res/CreateOrderSheetResponse.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/res/OrderResponse.java
Labels: ⭐️ Feat

#11 Feat/#5 coupon interface
  src/main/java/com/programmers/smrtstore/coupon/application/AdminCouponService.java
  src/main/java/com/programmers/smrtstore/coupon/application/CouponService.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/BenefitUnitType.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/Coupon.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/CouponPublicationType.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/CouponQuantity.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/CouponType.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/CustomerManageBenefitType.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/ProductCoupon.java
  src/main/java/com/programmers/smrtstore/coupon/domain/entity/UserCoupon.java
  src/main/java/com/programmers/smrtstore/coupon/infrastructure/CouponJpaRepository.java
  src/main/java/com/programmers/smrtstore/coupon/infrastructure/ProductCouponJpaRepository.java
  src/main/java/com/programmers/smrtstore/coupon/infrastructure/UserCouponJpaRepository.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/req/CreateCouponRequest.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/req/OrderCouponRequest.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/req/SaveCouponRequest.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/req/UpdateUserCouponRequest.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/res/CouponResponse.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/res/CreateCouponResponse.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/res/OrderCouponResponse.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/res/ProductCouponResponse.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/res/SaveCouponResponse.java
  src/main/java/com/programmers/smrtstore/coupon/presentation/res/UserCouponResponse.java
Labels: ⭐️ Feat

#9 Feat/#3 point interface
  build.gradle
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/Point.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/PointDetail.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/PointStatus.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/req/FindPointByIssuedDateRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/req/PointDetailRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/req/PointRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/req/UsePointRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/res/PointResponse.java
Labels: ⭐️ Feat

#8 Feat/#7 keep interface
  build.gradle
  src/main/java/com/programmers/smrtstore/domain/keep/application/KeepService.java
  src/main/java/com/programmers/smrtstore/domain/keep/domain/entity/Keep.java
  src/main/java/com/programmers/smrtstore/domain/keep/infrastructure/KeepJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/req/CreateKeepRequest.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/req/DeleteKeepRequest.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/req/FindKeepByCategoryRequest.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/CreateKeepResponse.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/DeleteKeepResponse.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/KeepResponse.java
Labels: ⭐️ Feat

#28 Feat/#4 product interface
  build.gradle
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductService.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Category.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductQuantity.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductAlreadyAvailableException.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductAlreadyReleasedException.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductNotAvailableException.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductQuantityRepository.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductRepository.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/UpdateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/CreateProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductResponse.java
Labels: ⭐️ Feat

#29 Feat/#1 Security Setting
  build.gradle
  src/main/java/com/programmers/smrtstore/core/config/SecurityConfiguration.java
  src/main/java/com/programmers/smrtstore/core/properties/JwtProperties.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/Jwt.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthentication.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationToken.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Auth.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Gender.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Role.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/infrastructure/UserRepository.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/LoginRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/SignUpUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/UpdateUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/SignUpUserResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/UserResponse.java
  src/main/java/com/programmers/smrtstore/util/DateStrategy.java
  src/test/java/com/programmers/smrtstore/core/properties/JwtTest.java
Labels: ⭐️ Feat

#37 Feat/#33 global exception handler
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/smrtstore/exception/dto/ErrorResponse.java
  src/main/java/com/programmers/smrtstore/exception/exceptionClass/CustomException.java
Labels: ⭐️ Feat

#39 [CHORE] testcontainers, querydsl 의존성 추가
  build.gradle
Labels: 🧹 Chore

#44 [CHORE] test 시 테스트컨테이너 사용할 수 있게 yml 추가
  .github/workflows/ci_gradle.yml
Labels: 🧹 Chore, 🚀 Infra

#49 Chore/#48 querydsl config
  build.gradle
  src/main/java/com/programmers/smrtstore/core/config/QueryDslConfiguration.java
Labels: 🧹 Chore

#46 Feat/#31 user service
  src/main/java/com/programmers/smrtstore/core/config/SecurityConfiguration.java
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Auth.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/exception/UserException.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/controller/AuthController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/controller/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/LoginRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/SignUpUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/DetailUserResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/SignUpUserResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/UserResponse.java
  src/main/java/com/programmers/smrtstore/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/smrtstore/exception/dto/ValidationErrorResponse.java
Labels: ⭐️ Feat, 🔄 Refactor, 🧹 Chore

#54 Feat/#26 product service
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/UpdateProductOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/UpdateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductOptionResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/UpdateProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Category.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/OptionTag.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductQuantity.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductAlreadyAvailableException.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductAlreadyReleasedException.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductException.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductNotAvailableException.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductOptionJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductQuantityJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/UpdateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/CreateProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductResponse.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: ⭐️ Feat

#55 Feat/#53 user service
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthentication.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/Auth.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/infrastructure/UserRepository.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/controller/AuthController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/controller/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/LoginRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/SignUpUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/UpdateUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/DetailAuthResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/DetailUserResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/SignUpUserResponse.java
Labels: ⭐️ Feat

#84 [CHORE] SMTP 라이브러리 추가, Guava 라이브러리 삭제
  build.gradle
Labels: 🧹 Chore

#75 Refact/#74 refact user 정보 보여주기
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/ProfileUserResponse.java
Labels: 🔄 Refactor

#77 Refact/#76 user update and delete
  src/main/java/com/programmers/smrtstore/domain/auth/application/AuthService.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/AuthRepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/AuthController.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/SignUpAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/UpdatePasswordRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/UpdateUserRequest.java
Labels: 🔄 Refactor

#91 Refactor/#90 Product 도메인 할인 가격 제공 방식 수정
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/UpdateProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductException.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: 🔄 Refactor

#93 Refact/#92 update user error
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
Labels: 🔄 Refactor

#79 [FEAT] Review 도메인 구현
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/Review.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/ReviewLike.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/ReviewScore.java
Labels: ⭐️ Feat

#70 Feat/#69 cart domain
  src/main/java/com/programmers/smrtstore/domain/cart/domain/entity/Cart.java
Labels: ⭐️ Feat

#72 Feat/#71 Auth Reissue 구현
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/AuthService.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/res/LoginResponse.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/res/ReissueResponse.java
  src/main/java/com/programmers/smrtstore/domain/auth/domain/entity/TokenEntity.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/AuthJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/AuthController.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/ReissueAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/res/DetailAuthAPIResponse.java
Labels: ⭐️ Feat, 🔄 Refactor

#73 Feat/#59 coupon download
  src/main/java/com/programmers/smrtstore/domain/auth/application/AuthService.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/res/LoginResponse.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/res/ReissueResponse.java
  src/main/java/com/programmers/smrtstore/domain/auth/domain/entity/TokenEntity.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/AuthRepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/AuthController.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/ReissueAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/SignUpAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/UpdatePasswordRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/res/DetailAuthAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/cart/domain/entity/Cart.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponQueryRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/CouponApiController.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/SaveCouponRequest.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/SaveCouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/UpdateProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductException.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/Review.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/ReviewLike.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/ReviewScore.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/UpdateUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/DetailUserResponse.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: ⭐️ Feat

#96 Revert "Feat/#59 coupon download"
  src/main/java/com/programmers/smrtstore/domain/auth/application/AuthService.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/res/LoginResponse.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/res/ReissueResponse.java
  src/main/java/com/programmers/smrtstore/domain/auth/domain/entity/TokenEntity.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/AuthJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityJPARepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/AuthController.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/ReissueAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/SignUpAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/req/UpdatePasswordRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/res/DetailAuthAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/cart/domain/entity/Cart.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponQueryRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/CouponApiController.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/SaveCouponRequest.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/SaveCouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/UpdateProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/exception/ProductException.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/Review.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/ReviewLike.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/ReviewScore.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/UpdateUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/ProfileUserResponse.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: 🐞 Bug
