Repository smRt-Egg/BE-05-smRt-store, pull requests merged in 2024-01, with the labels that each got.

#101 refactor/#100 product column type change
  src/main/java/com/programmers/smrtstore/domain/keep/application/KeepService.java
  src/main/java/com/programmers/smrtstore/domain/keep/infrastructure/KeepRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/keep/infrastructure/KeepRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/req/FindKeepByCategoryRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/UpdateProductOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/UpdateProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductOptionResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/UpdateProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/enums/Category.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/enums/OptionTag.java
  src/test/java/com/programmers/smrtstore/domain/keep/application/KeepServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: 🔄 Refactor

#99 Feat/#61 user montly used amount
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/order/application/OrderService.java
  src/main/java/com/programmers/smrtstore/domain/order/application/OrderServiceImpl.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/enums/OrderStatus.java
  src/main/java/com/programmers/smrtstore/domain/order/exception/OrderException.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/res/OrderResponse.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/res/OrderedProductResponse.java
  src/main/java/com/programmers/smrtstore/exception/exceptionClass/CustomException.java
  src/main/java/com/programmers/smrtstore/util/DateTimeUtils.java
Labels: ⭐️ Feat

#114 [RENAME] *JPARepository to *JpaRepository
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductService.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductOptionJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductQuantityJpaRepository.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: 💇🏻‍♀️ Style, 🔄 Refactor

#115 Feat/#112 security exception handling
  src/main/java/com/programmers/smrtstore/core/config/SecurityConfiguration.java
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/AuthService.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/AuthJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/TokenEntityJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/programmers/smrtstore/exception/GlobalExceptionHandler.java
Labels: ⭐️ Feat

#95 Feat/#94 Cart Service 구현 - Cart 물품 추가, 조회, 삭제
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/CartService.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/dto/req/CreateCartRequest.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/dto/req/UpdateCartRequest.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/dto/res/CartResponse.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/dto/res/CreateCartResponse.java
  src/main/java/com/programmers/smrtstore/domain/cart/domain/entity/Cart.java
  src/main/java/com/programmers/smrtstore/domain/cart/exception/CartException.java
  src/main/java/com/programmers/smrtstore/domain/cart/infrastructure/CartJPARepository.java
  src/test/java/com/programmers/smrtstore/domain/cart/application/CartServiceTest.java
Labels: ⭐️ Feat

#51 [FEAT] Keep Controller 기능 구현
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/controller/KeepController.java
Labels: ⭐️ Feat

#108 Feat/#27, 117 Point Service 구현 - 포인트 적립금 계산 및 적립 기능 구현
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/PointDetailRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/PointRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/res/OrderExpectedPointDto.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/res/PointResponse.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/Point.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/PointDetail.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/PointStatus.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/enums/PointStatus.java
  src/main/java/com/programmers/smrtstore/domain/point/exception/PointException.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/req/PointDetailRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/req/PointRequest.java
Labels: ⭐️ Feat

#106 Feat/#87 coupon product
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductDiscountCalculator.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponAvailableUser.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponQuantity.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/enums/CouponType.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/exception/CouponException.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponAvailableProductJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/CreateCouponRequest.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/SaveCouponRequest.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/CouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/CreateCouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/DiscountCoupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/ProductCouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/SaveCouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/UserCouponResponse.java
Labels: ⭐️ Feat, 🔄 Refactor

#105 Feat/#97 review service
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/review/application/ReviewService.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/req/CreateReviewRequest.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/req/ReviewLikeRequest.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/req/UpdateReviewRequest.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/CreateReviewResponse.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/ReviewDetailResponse.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/ReviewResponse.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/Review.java
  src/main/java/com/programmers/smrtstore/domain/review/exception/ReviewException.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewLikeJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewQueryRepository.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewQueryRepositoryImpl.java
Labels: ⭐️ Feat

#131 Feat/#128 user shipping address 조회, 등록 구현
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/dto/res/SignUpResponse.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/AuthController.java
  src/main/java/com/programmers/smrtstore/domain/auth/presentation/dto/res/SignUpAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponAvailableUser.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/application/vo/AggUserShippingInfo.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/CreateShippingRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/UpdateUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/CreateShippingResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/DeliveryAddressBook.java
  src/test/java/com/programmers/smrtstore/domain/cart/application/CartServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/user/application/UserServiceTest.java
Labels: ⭐️ Feat, ✅ Test

#143 Feat/#30 order sheet
  src/main/java/com/programmers/smrtstore/domain/order/application/OrderService.java
  src/main/java/com/programmers/smrtstore/domain/order/application/OrderServiceImpl.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/Order.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/OrderedProduct.java
  src/main/java/com/programmers/smrtstore/domain/order/domain/entity/enums/DeliveryMethodType.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/application/OrderSheetService.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/domain/entity/OrderSheet.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/req/CreateOrderSheetRequest.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/req/CreateOrderedProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/req/OrderSheetProductOptionReq.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/res/OrderSheetOrdererInfo.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/res/OrderSheetResponse.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/ApplicableDeliveryFeeCoupons.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/ApplicableProductCoupons.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/CouponApplyResult.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/OrderSheetCouponInfo.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/OrderSheetDiscountedProductInfo.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/OrderSheetPayMethod.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/OrderSheetProductInfo.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/OrderSheetProductOption.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/OrderSheetUserPointInfo.java
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/SelectedCoupons.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/req/CreateOrderSheetRequest.java
  src/main/java/com/programmers/smrtstore/domain/order/presentation/dto/res/CreateOrderSheetResponse.java
Labels: ⭐️ Feat

#129 Feat/#119 coupon transaction
  src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponCommonTransaction.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponTransaction.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponUsageTransaction.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/enums/CouponStatus.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponCommonTransactionJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponUsageTransactionJpaRepository.java
Labels: ⭐️ Feat

#103 [FEAT] keep response 반환 타입 수정
  src/main/java/com/programmers/smrtstore/domain/keep/application/KeepService.java
  src/main/java/com/programmers/smrtstore/domain/keep/domain/entity/Keep.java
  src/main/java/com/programmers/smrtstore/domain/keep/infrastructure/KeepJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/keep/infrastructure/KeepRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/keep/infrastructure/KeepRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/controller/KeepController.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/CreateKeepResponse.java
  src/main/java/com/programmers/smrtstore/domain/keep/presentation/dto/res/KeepResponse.java
  src/test/java/com/programmers/smrtstore/domain/keep/application/KeepServiceTest.java
Labels: 🔄 Refactor

#104 Feat/#52 qna 기능 구현
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
  src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductAnswer.java
  src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductQuestion.java
  src/main/java/com/programmers/smrtstore/domain/qna/exception/QnAException.java
  src/main/java/com/programmers/smrtstore/domain/qna/infrastructure/ProductAnswerRepository.java
  src/main/java/com/programmers/smrtstore/domain/qna/infrastructure/ProductQuestionRepository.java
  src/main/java/com/programmers/smrtstore/domain/qna/infrastructure/ProductQuestionRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/qna/infrastructure/ProductQuestionRepositoryImpl.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/controller/ProductQnAController.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/req/CreateAnswerRequest.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/req/CreateQuestionRequest.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/req/FindQuestionRequest.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/req/UpdateAnswerRequest.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/req/UpdateQuestionRequest.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/AnswerResponse.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/CreateQuestionResponse.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/DeleteQuestionResponse.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/QuestionResponse.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/UpdateAnswerResponse.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/dto/res/UpdateQuestionResponse.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
Labels: ⭐️ Feat

#133 Feat/#109 Point Service 구현 - 상품 구매 시 적립 가능한 최대 적립 포인트 계산 기능 구현
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/res/ProductEstimatedPointDto.java
Labels: ⭐️ Feat

#155 Fix/#109 메서드명 오류 수정
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
Labels: 🐞 Bug

#156 FIX/#86 keep 및 qna 테스트 오류 수정 (Product 테이블 변수 수정 이슈)
  src/test/java/com/programmers/smrtstore/domain/keep/application/KeepServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
Labels: 🔄 Refactor

#141 Feat/#134 product controller 목록조회, 생성 기능 구현
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductThumbnailResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductDetailOptionAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/ProductDiscountRatioAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductAdditionalOptionAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailOptionAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailOptionPriceResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDiscountAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductThumbnailAPIResponse.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: ⭐️ Feat

#123 Feat/#64 Point Service 구현 - 포인트 적립 취소 및 상세 이력 저장 기능 구현
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/PointDetailRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/PointRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/UsePointRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/Point.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/PointDetail.java
  src/main/java/com/programmers/smrtstore/domain/point/exception/PointException.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/dto/req/UsePointRequest.java
Labels: ⭐️ Feat

#158 [FIX] deletedAt 포함 Query 수정
  src/main/java/com/programmers/smrtstore/domain/auth/infrastructure/AuthJpaRepository.java
Labels: 🔄 Refactor

#154 Feat/#97 review service
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/order/infrastructure/OrderRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/review/application/ReviewService.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
Labels: ✅ Test

#160 [REFACT] cartService createCart 리펙토링
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/CartService.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/dto/req/UpdateCartOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/dto/req/UpdateCartQuantityRequest.java
  src/main/java/com/programmers/smrtstore/domain/cart/domain/entity/Cart.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/UsePointRequest.java
  src/main/java/com/programmers/smrtstore/domain/review/application/ReviewService.java
Labels: 🔄 Refactor

#118 Feat/#63 Point Service 구현 - 포인트 사용 및 상세 차감 이력 저장 기능 구현
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/PointRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/UsePointRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/res/PointDetailCustomResponse.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/Point.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointRepositoryCustomImpl.java
Labels: ⭐️ Feat

#125 Feat/#65 Point Service 구현 - 포인트 사용 취소 처리 및 상세 이력 저장 기능 구현
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointFacade.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointFacadeImpl.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/res/PointDetailResponse.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/Point.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailRepositoryCustomImpl.java
Labels: ⭐️ Feat

#161 [FIX] 잘못된 메서드 arg 제거
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
Labels: 🐞 Bug

#163 Refact/#162 product service
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/Point.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductAdditionalService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductCommonService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductDetailService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductOrderService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductDetailOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/ProductDetailOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/ProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductAdditionalOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductDetailOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/enums/Category.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/vo/OptionNameTypes.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/vo/OptionNames.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
  src/test/java/com/programmers/smrtstore/domain/keep/application/KeepServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
Labels: 🔄 Refactor

#165 [RENAME] userRepository 이름 변경
  src/main/java/com/programmers/smrtstore/domain/auth/application/AuthService.java
  src/main/java/com/programmers/smrtstore/domain/cart/application/CartService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/CouponService.java
  src/main/java/com/programmers/smrtstore/domain/keep/application/KeepService.java
  src/main/java/com/programmers/smrtstore/domain/order/application/OrderServiceImpl.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQnAService.java
  src/main/java/com/programmers/smrtstore/domain/review/application/ReviewService.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/infrastructure/UserJpaRepository.java
  src/test/java/com/programmers/smrtstore/domain/keep/application/KeepServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/user/application/UserServiceTest.java
Labels: 🔄 Refactor

#173 [REFACT] Point, PointDetail 컬럼명 수정
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/Point.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/PointDetail.java
Labels: 🔄 Refactor

#171 [FEAT] Product 검증 로직 추가
  src/main/java/com/programmers/smrtstore/domain/cart/application/CartService.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductJpaRepository.java
Labels: ⭐️ Feat

#144 Feat/#126 Point Service 구현 - 포인트 만료 처리 기능 구현
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointFacade.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointFacadeImpl.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/res/ExpiredPointDetailResponse.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/PointDetail.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailRepositoryCustomImpl.java
Labels: ⭐️ Feat

#181 Test/#180 product service
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductDetailOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/vo/OptionNameTypes.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/vo/OptionNames.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductAdditionalServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductDetailServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: ✅ Test

#178 [FEAT] product endpoint 기능 구현
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductAdditionalService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductDetailService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/ProductAdditionalOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/ProductDetailOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductDetailResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductQuantity.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAdditionalOptionAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/UpdateAdditionalOptionAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/UpdateDetailOptionAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/UpdateProductAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailAPIResponse.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductAdditionalServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductDetailServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
Labels: ⭐️ Feat

#187 Refact/#185 remove product additional option
  src/main/java/com/programmers/smrtstore/domain/order/orderSheet/presentation/dto/vo/OrderSheetProductOption.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductAdditionalService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductDetailService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductOrderService.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/CreateProductAdditionalOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/req/ProductAdditionalOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductAdditionalOptionResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/application/dto/res/ProductResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductAdditionalOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductDetailOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductOption.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/enums/OptionType.java
  src/main/java/com/programmers/smrtstore/domain/product/infrastructure/ProductAdditionalOptionJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/CreateProductAdditionalOptionAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/UpdateAdditionalOptionAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductAdditionalOptionAPIResponse.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductAdditionalServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductDetailServiceTest.java
Labels: 🔄 Refactor

#186 Feat/#166 cart controller
  src/main/java/com/programmers/smrtstore/domain/cart/application/CartService.java
  src/main/java/com/programmers/smrtstore/domain/cart/presentation/CartController.java
  src/main/java/com/programmers/smrtstore/domain/cart/presentation/dto/req/CreateCartRequest.java
  src/main/java/com/programmers/smrtstore/domain/cart/presentation/dto/req/UpdateCartOptionRequest.java
  src/main/java/com/programmers/smrtstore/domain/cart/presentation/dto/req/UpdateCartQuantityRequest.java
  src/main/java/com/programmers/smrtstore/domain/cart/presentation/dto/res/CartResponse.java
  src/main/java/com/programmers/smrtstore/domain/cart/presentation/dto/res/CreateCartResponse.java
Labels: ⭐️ Feat, 🔄 Refactor

#153 Feat/#138 Point Service 구현 - 월별, 상태별 조회 기능 구현
  src/main/java/com/programmers/smrtstore/domain/point/application/PointFacade.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointFacadeImpl.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/dto/req/PointHistoryRequest.java
  src/main/java/com/programmers/smrtstore/domain/point/domain/entity/vo/TradeDateRange.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointRepositoryCustomImpl.java
Labels: ⭐️ Feat

#195 Feat/#184 review controller 및 미작성 리뷰 갯수 반환 함수 구현
  src/main/java/com/programmers/smrtstore/domain/review/application/ReviewService.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewQueryRepository.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewQueryRepositoryImpl.java
  src/main/java/com/programmers/smrtstore/domain/review/presentation/ReviewController.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
Labels: ⭐️ Feat

#168 Feat/#167 admin coupon service
  src/main/java/com/programmers/smrtstore/SmRtStoreApplication.java
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/UserCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponAvailableUser.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/enums/CouponStatus.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponAvailableProductJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponAvailableUserJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
Labels: ⭐️ Feat

#204 Feat/#203 user point update
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
Labels: ⭐️ Feat

#194 Feat/#192 user identify verification
  build.gradle
  src/main/java/com/programmers/smrtstore/core/config/RedisConfig.java
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/user/application/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/application/service/MailService.java
  src/main/java/com/programmers/smrtstore/domain/user/application/service/RedisService.java
  src/main/java/com/programmers/smrtstore/domain/user/application/service/ShippingAddressService.java
  src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/infrastructure/UserJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/controller/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/facade/UserFacade.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/facade/UserFacadeImpl.java
  src/test/java/com/programmers/smrtstore/SmRtStoreApplicationTests.java
  src/test/java/com/programmers/smrtstore/core/config/RedisTestConfig.java
  src/test/java/com/programmers/smrtstore/domain/keep/application/KeepServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductDetailServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/user/application/UserServiceTest.java
Labels: ⭐️ Feat, ✅ Test, 🧹 Chore

#214 [CHORE] cd에서 docker로 redis 띄우기
  .github/workflows/cd_gradle.yml
Labels: 🧹 Chore

#198 [REFACT] ErrorCode 이름 수정 및 통합
  src/main/java/com/programmers/smrtstore/common/resolver/UserIdResolver.java
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/auth/application/AuthService.java
  src/main/java/com/programmers/smrtstore/domain/auth/domain/entity/Auth.java
  src/main/java/com/programmers/smrtstore/domain/cart/domain/entity/Cart.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponAvailableUser.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderedProduct/application/OrderedProductService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderedProduct/domain/entity/OrderedProduct.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductCommonService.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/user/application/service/UserService.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/ShippingAddress.java
  src/main/java/com/programmers/smrtstore/domain/user/domain/entity/User.java
Labels: 🔄 Refactor

#219 Feat/#196 order sheet create get
  src/main/java/com/programmers/smrtstore/common/base/TimestampBaseEntity.java
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/delivery/DeliveryException.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/delivery/DeliveryProperties.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/domain/entity/enums/DeliveryMethodType.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/infrastructure/OrderRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/application/OrderSheetService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/domain/entity/OrderSheet.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/infrastructure/OrderSheetJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/OrderSheetController.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/req/CreateOrderSheetRequest.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/req/OrderSheetProductOptionReq.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/res/OrderSheetDetailViewResponse.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/res/OrderSheetOrdererInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/OrderSheetCouponInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/OrderSheetProductInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/OrderSheetProductOption.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/OrderSheetProductOptionResponse.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/OrderSheetUserPointInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderedProduct/application/OrderedProductService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderedProduct/application/dto/CreateOrderedProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderedProduct/domain/entity/OrderedProduct.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/Product.java
  src/main/java/com/programmers/smrtstore/domain/product/domain/entity/ProductDetailOption.java
Labels: ⭐️ Feat

#212 Feat/#206 coupon domain 변경 및 product detail 페이지 쿠폰 로직 변경
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/AdminCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductDiscountCalculator.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/Coupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponAvailableProduct.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/vo/CouponValue.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/facade/CouponQuantityFacade.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/CreateCouponAvailableProductRequest.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/CreateCouponAvailableUserRequest.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/req/CreateCouponRequest.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/CouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/DiscountCoupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/ProductCouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/UserCouponResponse.java
Labels: 🔄 Refactor

#218 [FIX] RedisConfig 주석 처리 해제
  src/main/java/com/programmers/smrtstore/core/config/RedisConfig.java
Labels: 🔄 Refactor

#205 Feat/#134 product detail page
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/vo/CouponBenefitsPolicy.java
  src/main/java/com/programmers/smrtstore/domain/point/presentation/vo/PointBenefits.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailOptionPriceResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailPageAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDiscountAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductThumbnailAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/facade/ProductServiceFacade.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/facade/ProductServiceFacadeImpl.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/vo/ProductDetailOptionPrice.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/vo/ProductOptionType.java
  src/main/java/com/programmers/smrtstore/domain/review/application/ReviewService.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/ReviewDetailResponse.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/ReviewStatisticsResponse.java
Labels: ⭐️ Feat

#227 [FIX] Product Controller 수정
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/vo/CouponBenefitsPolicy.java
  src/main/java/com/programmers/smrtstore/domain/product/application/ProductService.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/ProductController.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/ProductDiscountRatioAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/req/UpdateProductAPIRequest.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailOptionAPIResponse.java
  src/main/java/com/programmers/smrtstore/domain/product/presentation/dto/res/ProductDetailPageAPIResponse.java
Labels: 🐞 Bug

#216 Feat/#215 order coupon dto
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductDiscountCalculator.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/CouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/ProductCouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/vo/CouponBenefitsPolicy.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/vo/DiscountCoupon.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/ApplicableDeliveryFeeCoupons.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/ApplicableProductCoupons.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/CouponApplyResult.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/OrderSheetCouponInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/SelectedCoupons.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderedProduct/domain/entity/OrderedProduct.java
Labels: 🔄 Refactor, 🧹 Chore

#221 Feat/#220 order coupon service
  src/main/java/com/programmers/smrtstore/domain/coupon/application/OrderCouponDiscountCalculator.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/OrderCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/ProductDiscountCalculator.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/coupon/infrastructure/CouponRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/vo/CartDiscountCoupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/vo/DiscountCoupon.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/vo/OrderDiscountCoupon.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/req/SelectedCouponsRequest.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/OrderSheetCouponInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/SelectedCoupons.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/vo/SelectedCouponsWithCouponApplyResult.java
Labels: ⭐️ Feat

#236 [FIX] final 키워드 추가
  src/main/java/com/programmers/smrtstore/domain/point/infrastructure/PointDetailRepositoryCustomImpl.java
Labels: 🐞 Bug

#234 [FEAT] User 의 주문 내역, User의 활성화된 주문 count 서비스 구현
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/application/OrderService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/application/OrderServiceImpl.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/domain/entity/enums/OrderStatus.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/infrastructure/OrderJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/presentation/dto/res/OrderPreviewResponse.java
Labels: ⭐️ Feat

#237 [FIX] TestContainers DDL 적용 및 이에 따른 테스트 수정
  .github/workflows/ci_gradle.yml
  .gitignore
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/ReviewLike.java
  src/test/java/com/programmers/smrtstore/domain/keep/application/KeepServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductDetailServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/product/application/ProductServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/user/application/UserServiceTest.java
Labels: 🐞 Bug

#240 README 수정
  README.md
Labels: 📑 Docs

#224 Feat/#223 coupon test
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponAvailableProduct.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponAvailableUser.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponCommonTransaction.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponTransaction.java
  src/main/java/com/programmers/smrtstore/domain/coupon/domain/entity/CouponUsageTransaction.java
  src/test/java/com/programmers/smrtstore/domain/coupon/domain/application/AdminCouponTest.java
  src/test/java/com/programmers/smrtstore/domain/coupon/domain/application/ProductCouponTest.java
  src/test/java/com/programmers/smrtstore/domain/coupon/domain/application/UserCouponTest.java
  src/test/resources/ddl.sql
Labels: ✅ Test

#245 [REFACT] 비율별 포인트 차감액과 orderedProductId를 이용한 '사용' 포인트 차감액 이력 로직 수정
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
Labels: 🔄 Refactor

#247 Feat/#246 coupon dto refactor
  src/main/java/com/programmers/smrtstore/domain/coupon/application/OrderCouponDiscountCalculator.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/OrderCouponService.java
  src/main/java/com/programmers/smrtstore/domain/coupon/presentation/res/CouponResponse.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/req/SelectedCouponsRequest.java
Labels: 🔄 Refactor

#226 [FEAT] 리뷰 생성 시 포인트 적립 기능 추가
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/infrastructure/OrderRepositoryCustom.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/infrastructure/OrderRepositoryCustomImpl.java
  src/main/java/com/programmers/smrtstore/domain/review/application/ReviewService.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/req/CreateReviewRequest.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/CreateReviewResponse.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/ReviewResponse.java
  src/main/java/com/programmers/smrtstore/domain/review/application/dto/res/UnWrittenReviewResponse.java
  src/main/java/com/programmers/smrtstore/domain/review/domain/entity/Review.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewQueryRepository.java
  src/main/java/com/programmers/smrtstore/domain/review/infrastructure/ReviewQueryRepositoryImpl.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
  src/test/resources/ddl.sql
Labels: ⭐️ Feat

#255 Feat/#241 order create
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/coupon/application/OrderCouponService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/delivery/entity/DeliveryInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/delivery/entity/vo/DeliveryAddress.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/delivery/entity/vo/ReceiverInfo.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/delivery/infrastructure/DeliveryInfoJpaRepository.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/application/OrderPointService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/application/OrderService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/application/OrderServiceImpl.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/application/SimpleIdGenerator.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/domain/entity/Order.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/presentation/dto/req/CreateDeliveryAddressRequest.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/presentation/dto/req/CreateOrderRequest.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/order/presentation/dto/res/OrderResponse.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/application/OrderSheetService.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/domain/entity/OrderSheet.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/domain/entity/vo/DeliveryOptions.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/req/SelectedCouponsRequest.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderSheet/presentation/dto/res/OrderSheetDetailViewResponse.java
  src/main/java/com/programmers/smrtstore/domain/orderManagement/orderedProduct/domain/entity/OrderedProduct.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointDetailService.java
  src/main/java/com/programmers/smrtstore/domain/point/application/PointService.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
  src/test/resources/ddl.sql
Labels: ⭐️ Feat

#191 [REFACTOR] qna 도메인 리펙토링
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/qna/application/ProductAnswerService.java
  src/main/java/com/programmers/smrtstore/domain/qna/application/ProductQuestionService.java
  src/main/java/com/programmers/smrtstore/domain/qna/domain/entity/ProductQuestion.java
  src/main/java/com/programmers/smrtstore/domain/qna/presentation/controller/ProductQnAController.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
Labels: ⭐️ Feat, 🔄 Refactor

#260 [FEAT] user myhome
  src/main/java/com/programmers/smrtstore/core/properties/ErrorCode.java
  src/main/java/com/programmers/smrtstore/domain/user/application/service/MyHomeService.java
  src/main/java/com/programmers/smrtstore/domain/user/infrastructure/UserQueryRepository.java
  src/main/java/com/programmers/smrtstore/domain/user/infrastructure/UserQueryRepositoryImpl.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/controller/UserController.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/req/DurationRequest.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyAllKeepsResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyCategoryKeepsResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyCouponsResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyHomeResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyOrdersResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyQnaResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyReviewsResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/dto/res/MyWritableReviewsResponse.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/facade/UserFacade.java
  src/main/java/com/programmers/smrtstore/domain/user/presentation/facade/UserFacadeImpl.java
  src/test/java/com/programmers/smrtstore/domain/coupon/domain/application/AdminCouponTest.java
  src/test/java/com/programmers/smrtstore/domain/coupon/domain/application/ProductCouponTest.java
  src/test/java/com/programmers/smrtstore/domain/coupon/domain/application/UserCouponTest.java
  src/test/java/com/programmers/smrtstore/domain/qna/application/ProductQnAServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/review/application/ReviewServiceTest.java
  src/test/java/com/programmers/smrtstore/domain/user/application/UserServiceTest.java
Labels: ⭐️ Feat
